build:
  image: ghcr.io/nixos/nix
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" flake check
    - nix --extra-experimental-features "nix-command flakes" build
    - cp -r result/* public/
  artifacts:
    paths:
      - public

deploy:
  image: gitlab.laas.fr:4567/gsaurel/talks
  stage: deploy
  only:
    refs:
      - main@gsaurel/teach
  variables:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=.known_hosts"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git checkout main
    - git reset --hard $CI_COMMIT_SHA
  script:
    - chmod -R a+rw public
    - touch public/20*/*/*.pdf
    - make -j deploy
    - git push git@github.com:nim65s/teach main
