image: gitlab.laas.fr:4567/gsaurel/teach

build:
  stage: build
  script:
    - make -j
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  only:
    refs:
      - main@gsaurel/teach
  variables:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=.known_hosts"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git checkout main
    - git reset --hard $CI_COMMIT_SHA
  script:
    - touch public/20*/*/*.pdf
    - make -j deploy
    - git push git@github.com:nim65s/teach main
