image: ghcr.io/nixos/nix

build:
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" flake check
    - nix --extra-experimental-features "nix-command flakes" build
    - cp result/* public/
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  only:
    refs:
      - main@gsaurel/teach
  variables:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=.known_hosts"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git checkout main
    - git reset --hard $CI_COMMIT_SHA
  script:
    - touch public/*.pdf
    - nix-shell -p gnumake -p rsync --command "make -j deploy"
    - git push git@github.com:nim65s/teach main
